name = "FluxOptics"
uuid = "5d1b044d-dcff-404c-be27-e1944ce84415"
authors = ["Nicolas Barr√©"]
version = "1.0.0-DEV"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
CUDAExt = "CUDA"

[compat]
AbstractFFTs = "1.5.0"
CUDA = "5.8.2"
ChainRulesCore = "1.25.2"
EllipsisNotation = "1.8.0"
FFTW = "1.9.0"
Flux = "0.16.4"
Functors = "0.5.2"
LinearAlgebra = "1.11.0"
Optimisers = "0.4.6"
Polynomials = "4.1.0"
Requires = "1.3.1"
Statistics = "1.11.1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
